
GET http://localhost:3001
###
POST http://localhost:3001/user/register
Content-Type: application/json

{
  "email": "LAM05@gmail.com",
  "password": "a123456@"
}
###
POST http://localhost:3001/user/refresh-token
###
POST http://localhost:3001/user/login
Content-Type: application/json

{
  "email": "lam04@gmail.com",
  "password": "a123456@"
}
###
POST http://localhost:3001/user/logout
###
POST http://localhost:3001/user/getLists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThkYmJmMjM3ODZkMmE0MjRiYzg5MzkiLCJpYXQiOjE2MzY4NjU5MDksImV4cCI6MTYzNjg2OTUwOX0.-Rn3jdRpzfxxgEyyJoE5383GRjUUAdPC3gBl1Vk2R9E
